--
-- 表的结构 `link`,存储链接url
--

CREATE TABLE [link] (
  [id] INTEGER NOT NULL ON CONFLICT FAIL PRIMARY KEY ON CONFLICT FAIL AUTOINCREMENT, 
  [gid] INTEGER NOT NULL ON CONFLICT FAIL, 
  [name] VARCHAR2(128) NOT NULL ON CONFLICT FAIL, 
  [url] VARCHAR2(128) NOT NULL ON CONFLICT FAIL, 
  [title] VARCHAR2(128));
  
  
--
-- 表的结构 `group`,存储分组
--
  
CREATE TABLE [group] (
  [id] INTEGER NOT NULL ON CONFLICT FAIL PRIMARY KEY ON CONFLICT FAIL AUTOINCREMENT, 
  [gid] INTEGER NOT NULL ON CONFLICT FAIL, 
  [name] VARCHAR2(64) NOT NULL ON CONFLICT FAIL);  